myproject/blog/urls.py
from django.urls import path
from blog.views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogPostListView.as_view(), name='list'),
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', BlogPostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BlogPostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete'),
]

myproject/myproject/urls.py
# myproject\urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from .views import RegisterView, ProfileView, email_verification, ResetView, PasswordResetDone, ResetConfirmView, \
    ResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users/password_reset/', ResetView.as_view(), name='password_reset'),
    path('done/', PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', ResetConfirmView.as_view(), name='password_confirm'),
    path('users/reset/compete/', ResetCompleteView.as_view(), name='complete'),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),
]

myproject/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None

    phone = models.CharField(max_length=255, verbose_name='Номер телефона', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=255, verbose_name='Страна')
    email = models.EmailField(unique=True, verbose_name='Почта')
    token = models.CharField(max_length=255, verbose_name='Token', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

myproject/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

myproject/users/views.py
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetCompleteView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
import secrets
from .forms import UserRegisterForm, UserProfileForm
from .models import User
from django.conf import settings

EMAIL_HOST_USER = settings.EMAIL_HOST_USER


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        host = self.request.get_host()
        url = f'http://{host}/users/email_confirm/{token}/'
        user.token = token
        user.save()
        send_mail(
            'Подтверждение почты',
            f'Перейдите по ссылке для подтверждения почты {url}',
            EMAIL_HOST_USER,
            [user.email],
            fail_silently=False,
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class ResetView(PasswordResetView):
    model = User
    template_name = 'users/resetview.html'
    email_template_name = 'users/password_reset_email.html'

    success_url = reverse_lazy('catalog:home')


class PasswordResetDone(PasswordResetDoneView):
    model = User
    template_name = 'users/password_reset_done.html'


class ResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:complete')


class ResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'

myproject/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Вход
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
                            <button type="submit" class="btn btn-success">Войти</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

myproject/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{%block content%}
пароль сброшен
{%endblock%}

myproject/users/templates/users/password_reset_confirm.html
{%extends 'base.html'%}
{%block content%}

<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Войти</h3>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}

                 <button type="submit">Сохранить</button>
            </form>
        </div>
    </div>
</div>

{%endblock%}

myproject/users/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <h1>Сброс пароля</h1>
    <p>Инструкция по установке пароля отправлена на электронную почту.</p>
    <p>Если вам не пришло письмо, убедитесь, что вы верно указали почту.</p>
{% endblock %}

myproject/users/templates/users/password_reset_email.html
{%autoescape off%}
сброс пароля
{{protocol}}://{{domain}}{%url 'users:password_confirm' uidb64=uid token=token%}

{%endautoescape%}

myproject/users/templates/users/password_reset_form.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <h1>Забыли свой пароль?</h1>
    <p>Введите свою почту для создания нового пароля</p>
    <form action="." method="post">
        {{ form.as_p }}
        <a href="{% url 'users:password_reset_done' %}">Отправить</a>
        {% csrf_token %}
    </form>
{% endblock %}

myproject/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Регистрация
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-success">Регистрация</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

myproject/users/templates/users/resetview.html
{%extends 'base.html'%}
{%block content%}

<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Войти</h3>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}

                <input class="btn btn-primary" type="submit"
                       value="Сброс ">
            </form>
        </div>
    </div>
</div>

{%endblock%}

myproject/users/templates/users/user_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Профиль
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Сохранить</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}