myproject/blog/urls.py
from django.urls import path
from blog.views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogPostListView.as_view(), name='list'),
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', BlogPostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BlogPostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete'),
]

myproject/myproject/urls.py
# myproject\urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class BlogPost(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='products/', verbose_name='Превью', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блоговая запись'
        verbose_name_plural = 'Блоговые записи'

myproject/blog/views.py
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from .models import BlogPost
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published=True)
        return queryset


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ('title', 'slug', 'content', 'image', 'published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ('title', 'slug', 'content', 'image', 'published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail', args=[self.object.pk])


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:list')

myproject/blog/templates/blog/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить блог "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myproject/blog/templates/blog/blogpost_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Информация о блоге{% endblock %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <p>Содержимое: {{ object.content }}</p>
    <p>Превью: {{ object.image }}</p>
    <p>Дата создания: {{ object.created_at }}</p>
    <p>Количество просмотров: {{ object.views_count }}</p>
{% endblock %}

myproject/blog/templates/blog/blogpost_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myproject/blog/templates/blog/blogpost_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-12 mb-5">
         <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить блог</a>
    </div>
    {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">
                            {{ object|title }}
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:detail' object.pk %}"
                               class="btn btn-sm btn-outline-secondary">Подробности</a>
                            <a href="{% url 'blog:update' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Редактировать</a>
                            <a href="{% url 'blog:delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}