myproject/blog/urls.py
from django.urls import path
from blog.views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogPostListView.as_view(), name='list'),
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', BlogPostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BlogPostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete'),
]

myproject/catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import CatalogConfig
from .views import HomeListView, ProductDetailView, ContactsTemplateView, ProductCreateView, ProductUpdateView, ProductDeleteView, CategoryListView


app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/create', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_confirm_delete'),
    path('category/', CategoryListView.as_view(), name='category')
]

myproject/myproject/urls.py
# myproject\urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from .views import RegisterView, ProfileView, email_verification, ResetView, PasswordResetDone, ResetConfirmView, \
    ResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users/password_reset/', ResetView.as_view(), name='password_reset'),
    path('done/', PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', ResetConfirmView.as_view(), name='password_confirm'),
    path('users/reset/compete/', ResetCompleteView.as_view(), name='complete'),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),
]

myproject/catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку', default=0)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', **NULLABLE)
    publication_sign = models.BooleanField(verbose_name='Признак публикации', default=False, **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

        permissions = [
            (
                'can_ban_publish_products',
                'Can ban posts'
            ),
            (
                'can_change_description_product',
                'can change description'
            ),
            (
                'can_change_category_product',
                'can change category'
            )
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.IntegerField(verbose_name='Номер версии')
    version_name = models.CharField(max_length=150, verbose_name='Название версии')
    current_version_indication = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return self.version_name

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

myproject/catalog/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from django import forms

from .models import Product, Version


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'category', 'price', 'publication_sign')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name',
            'description',
            'image',
            'category',
            'price',
            'publication_sign',
            Submit('submit', 'Submit', css_class='btn-primary')
        )

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        if cleaned_data.lower() in (
                'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'обман', 'полиция',
                'радар'):
            raise forms.ValidationError(f"Нельзя использовать слово {cleaned_data} в названии")
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        if cleaned_data.lower() in (
                'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'обман', 'полиция',
                'радар'):
            raise forms.ValidationError(f"Нельзя использовать слово {cleaned_data} в описании")
        return cleaned_data


class ProductModeratorForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('description', 'category')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'description',
            'category',
            Submit('submit', 'Submit', css_class='btn-primary')
        )

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        if cleaned_data.lower() in (
                'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'обман', 'полиция',
                'радар'):
            raise forms.ValidationError(f"Нельзя использовать слово {cleaned_data} в описании")
        return cleaned_data


class VersionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'product',
            'number',
            'version_name',
            'current_version_indication',
            Submit('submit', 'Submit', css_class='btn-primary')
        )

    class Meta:
        model = Version
        fields = '__all__'

myproject/catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from .forms import ProductForm, VersionForm, ProductModeratorForm
from .management.commands.mail import send_order_email
from .models import Product, Version, Category
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from .services.category import all_category


class HomeListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'product_list.html'

    def get_queryset(self):
        return Product.objects.prefetch_related('version_set')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        is_moderator = user.groups.filter(name='moderators').exists()
        context['is_moderator'] = is_moderator
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'product/product_detail.html'


class ContactsTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'contacts/contacts.html'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')
    template_name = 'product/product_form.html'

    def form_valid(self, form):
        instance = form.save()
        instance.author = self.request.user
        send_order_email()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')
    template_name = 'product/product_form_formset.html'

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     return kwargs

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        user = self.request.user
        is_moderator = user.groups.filter(name='moderators').exists()
        if is_moderator:
            context_data['show_version_form'] = False  # Устанавливаем флаг как False для модераторов
        else:
            VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
            if self.request.method == 'POST':
                context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
            else:
                context_data['formset'] = VersionFormset(instance=self.object)
            context_data['show_version_form'] = True  # Устанавливаем флаг как True для остальных пользователей
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data.get('formset')

        form_valid = super().form_valid(form)
        if formset is not None and formset.is_valid():
            formset.instance = self.object
            formset.save()
        return form_valid

    def test_func(self):
        user = self.request.user
        obj = self.get_object()

        is_author = user = obj.author

        is_moderator = user.groups.filter(name='moderators').exists()
        # return user.groups.filter(name='moderators').exists() or user == obj.author
        return is_author or is_moderator

    def get_form_class(self):
        user = self.request.user
        if user == self.object.author:
            return ProductForm
        # elif user.has_perm('catalog.can_change_description_product') and user.has_perm('catalog.can_change_category_product'):
        elif user.groups.filter(name='moderators').exists():
            return ProductModeratorForm
        else:
            raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')
    template_name = 'product/product_confirm_delete.html'


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    template_name = 'version/version_form.html'
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['version_form'] = self.get_form()
        return context_data


class CategoryListView(ListView):
    model = Category
    template_name = 'category/category_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['categories'] = all_category()
        return context

myproject/catalog/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Продуктовая{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Продуктовая</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог продуктов</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:category' %}">Список категорий</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блоги</a>
            {% if user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
                                <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            {% else %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
        </nav>
    </div>
    <div class='ms-5 mb-4'>
            <a class="btn btn-outline-primary" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
        </div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>

myproject/catalog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <div class="row text-center">
        {% for product in products %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ product.description|slice:":100" }}</p>
                        <h1 class="card-title pricing-card-title">Цена: {{ product.price }} рублей</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <img class="card-img-top" src="{% mymedia product.image %}" width="300" height="200" >
                        </ul>
                         <a href="{% url 'catalog:product_detail' product.id %}" class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

myproject/catalog/templates/product_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <div class="row text-center">
        {% for product in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ product.description|slice:":100" }}</p>
                        <h1 class="card-title pricing-card-title">Цена: {{ product.price }} рублей</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <img class="card-img-top" src="{% mymedia product.image %}" width="300" height="200">
                            {% for version in product.version_set.all %}
                                {% if version.current_version_indication %}
                                    <p><strong>Текущая версия:</strong> {{ version.version_name }} (№{{ version.number }})</p>
                                {% else %}
                                    <p><strong>Версия:</strong> {{ version.version_name }} (№{{ version.number }})</p>
                                {% endif %}
                            {% endfor %}
                        </ul>
                        <a href="{% url 'catalog:product_detail' product.id %}" class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>

                        {% if product.author == user or is_moderator %}
                            <a href="{% url 'catalog:product_update' product.id %}" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                        {% endif %}
                        <a href="{% url 'catalog:product_confirm_delete' product.id %}" class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}